version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mapeando volume para o código Django
    env_file:
      - .env
    networks:
      - nginx-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Corrigido para carregar a configuração correta do Nginx
      - ./certs/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro  # Certificado
      - ./certs/privkey.pem:/etc/ssl/private/privkey.pem:ro  # Chave privada
    depends_on:
      - app
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
