version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mapeando volume para o código Django
    env_file:
      - .env
    networks:
      - nginx-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Configuração do Nginx
      - ./nginx/ssl:/etc/letsencrypt  # Volume para os certificados SSL
    depends_on:
      - app
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
