version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Volume mapeado corretamente
    command: gunicorn --bind 0.0.0.0:8000 project.wsgi:application  # Corrigido para o caminho correto
    env_file:
      - .env  # Lê o arquivo .env com as variáveis de ambiente
